# Generated by Django 3.0.5 on 2020-04-12 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sesiones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuario', models.IntegerField()),
                ('Dispositivo', models.CharField(max_length=50)),
                ('Creacion', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField()),
                ('MedioAuth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.Medio')),
            ],
        ),
        migrations.CreateModel(
            name='CuentasEnlazadas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdUsuario', models.IntegerField()),
                ('CorreoEnlazado', models.EmailField(max_length=254)),
                ('MedioAuth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Account.Medio')),
            ],
        ),
    ]
